### ISSUE TITLE
MessageListener doesn't work when RSBot is minimized

### ISSUE THREAD

**Issue by PorkScripts** [powerbot/powerbot#1099]
The MessageListener's messaged method isn't firing when messages are received while RSBot is minimized. When RSBot is maximized, the messaged method is called all at once for all messaged received while the client was minimized.

I'm using Windows 7, Java 8u66 JRE 64-bit. I've been experiencing this problem since RSBot 7 was released.

**Comment by Timer** [comment]
@Paris this is because we disable painting when the bot is minimized ...

**Comment by Timer** [comment]
@Paris simply spinning this up on another thread is a dirty solution because the event manager ensures proper cleanup on context recreation and other things, it would be quite a hassle actually. It's also worth noting some people rely on the paint thread for monitoring in their scripts so I think we should re-evaluation the disable of paint when iconified, what do you think?

**Comment by Paris** [comment]
Fixed for next version.
