### ISSUE TITLE
Java platform SE Binary has stopped working

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1190]
http://www.powerbot.org/community/topic/1297193-javatm-platform-se-binary/
http://www.powerbot.org/community/topic/1296956-rs3-exe-and-jar-crashing/
http://www.powerbot.org/community/topic/1296766-os-bot-constantly-crashing/
http://www.powerbot.org/community/topic/1296917-old-school-keeps-crashing/

Since 7019

Only user to reply and supply the crash log was
http://pastebin.com/raw/kUFStPZu

**Comment by ChrisBPB** [comment]
2 people of the 3 who replied claim no hs_err file was generated

**Comment by ChrisBPB** [comment]
4 of 5 now claim no hs_err_pid was generated, possibly 4 of 6 but I think the 6th guy posted a hs_err_pid from something else so I didn't count it.

**Comment by Paris** [comment]
I read through the threads and it seems like one person says they also got crashes in the official client, another person got hacked (not sure how this is related) and another didn't get crashes on a competing client. Since this is very difficult to identify and seems to happen in a small number of cases I'll close it for now, but please re-open with additional info if you have any.
