### ISSUE TITLE
Inventory items cant be accsessed

### ISSUE THREAD

**Issue by LuggePB** [powerbot/powerbot#1438]
The items of the inventory cannot be accessed if the inventory is not visible.
I belief that is trough an outdated widget setting, because the widget refereed to, when the inventory is not opened, is not existing.

`Component c = ctx.widgets.widget(149).component(0);
		if (!c.visible()) {
			c = ctx.widgets.widget(301).component(0);
		}`

instead the widget 149 is always valid (except trading/banking).
this occurs @rt4.Inventory in from line 36 to 39 and from line 56 to 58.

**Comment by Timer** [comment]
So open the inventory before querying it; some people use the cached results.

**Comment by ArtificialPB** [comment]
@Timer The problem is when an interface like fairy ring travel log is opened, which blocks the inventory. Refreshing the query returns that there are no items in inventory. I suggest a fallback to 149 widget if no other are visible (bank, trading interface). Just change code at https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/Inventory.java#L31-L34 to:
```
Component c = ctx.widgets.widget(301).component(0);
		if (!c.visible()) {
			c = ctx.widgets.widget(149).component(0);
		}
```
