### ISSUE TITLE
AbstractScript getStorageDirectory incorrect for Mac

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1892]
I'm on windows so I don't know the best way to get the directory on Mac, but I've been told that my script isn't saving any files by someone using a Mac.

configFile = new File(ctx.controller.script().getStorageDirectory(), "config.properties");

What has worked for iDzn on the forums is

`
username = System.getProperty("user.home");
        os = System.getProperty("os.name");

 if (os.contains("Mac")) {

            final String FILENAME = username + "//Library//RSBot//save.txt";

            File f = new File(FILENAME);

}
`

**Comment by ChrisBPB** [comment]
There may be confusion due to assumptions, however it isn't intended to save in /Library/RSBot - whilst that is the essentially the APPDATA for Mac machines it is not the default temp directory for Java applications.

I just tested it and ctx.controller.script().getStorageDirectory() is returning the correct path, so we would need to see your implementation to investigate.

**Comment by ChrisBPB** [comment]
closed due to inactivity
