### ISSUE TITLE
Support for new Withdraw X functionality

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1945]
Latest updated added the mobile banking interface enabling a single left click to perform what would previously be a right-click option.

Judging by how banking currently works, if the withdraw method is already set, the client will do a single left click accordingly.
e.g. User withdraws X as 14 and sets withdraw mode to X. Client will left click if told to withdraw 14.

Hence, the functions required would simply be to toggle the withdraw mode.

**Comment by ChrisBPB** [comment]
Is this not supported by default? If the first menu command is equal to the command we want to execute it will left click instead of right click by default as per https://github.com/powerbot/powerbot/blob/2213e44e5b43615d1325eb8a4a4d7a7f99e1f423/src/main/java/org/powerbot/script/rt4/Menu.java#L139


Was this issue made because that isn't happening or is this unverified?

**Comment by ChrisBPB** [comment]
sorry, to clarify you want a method to click the Quantity option or a method where you can force left click if it's available ?

**Comment by ChrisBPB** [comment]
Will be done with todays banking fix update, if you have feedback on it pls post asap as we need to get banking fixed asap ofcourse
https://github.com/powerbot/powerbot/pull/1947
