### ISSUE TITLE
RT4 Tilepath.next() not null safe

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1983]
Easiest way to replicate is to create a path on ground floor, go up a ladder and attempt to get the next tile. Tilepath.next() returns null.

If not checked, attempting to step towards Tile.NIL may cause unexpected behaviour which is why it might have been kept as null.

**Comment by Mkerian10** [comment]
I don't see where the leak is. TilePath#traverse checks for null, where exactly is the NPE occurring? It seems like the only way you'd get an NPE is if you're using TilePath in an undefined way (e.g. yourself)

**Comment by tanlines** [comment]
https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/TilePath.java#L99

**Comment by Mkerian10** [comment]
I personally don't think it's a big deal, however returning Tile.NIL would be acceptable here I believe.

I think null is better though, because in general it allows for better understanding of what's going on. A new user won't be using this function so it's not needed to protect them, I think in this case it's better to know where the issue is being caused rather than returning nil

**Comment by Strikegently** [comment]
Changing the expected behavior of a method would result in potential breakages in existing scripts; as such, this will not be changed.
