### ISSUE TITLE
Dynamic object/npc support

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#878]
Methods to check if entity is dynamic and getting their children. This is for both rt4 and rt6.

**Comment by Timer** [comment]
Object already does this... I don't know what you mean with Npcs.

**Comment by ArtificialPB** [comment]
So this means it's already supported in the most recently released client version? As I can't find any related methods in the API for objects.

For npcs I mean the same thing as for objects. They can also be dynamic. Take those "alive" trees on the way to Draynor manor for example. Their id is 152.

This will allow us to check for a state of an entity from varpbits without the need to provide some external data dumps (Farming scripts, etc...).

**Comment by Timer** [comment]
Yes, the current API automagically finds and replaces the ids for dynamic OBJECTS.
No special API needed.

**Comment by ArtificialPB** [comment]
I see. Will there be any methods for us to use to read from rs cache? Or we'll still need to use external cache readers to dump the data from the cache in advance?

**Comment by Timer** [comment]
What data do you want ...?

**Comment by ArtificialPB** [comment]
Accessing object definitions when they are not in loaded area, grabbing varps related to dynamic objects state on the go, etc... One example of use would be in web walking, where you can check if a faster route is available based on objects state without being in the loaded area.

**Comment by Timer** [comment]
We did not have any plans to release direct cache methods, but may allow you to create a wrapper -- the wrapper will have all functions relating to cache grabbable information.

**Comment by Logicail** [comment]
It's pretty essential to be able to get definitions when not in the region

* A useful one for RT4 objects is opcode 40, default colours and their substitution. I used it to identify rocks on tutorial island
* If you haven't already add quests, most important is status (not started, in progress, completed), quest point, quest completion and skill requirements may be useful if anyone wants to make a quester again
* Item actions/equipedactions (uses opcode 249)/groundactions

I wouldn't expect you to load everything from the definition since most people wont use it so it would be a waste, maybe a method so we can request the data for a specific opcode, callback(opcode, data[]) so we can just get the part we want without dealing with reading the rest of the structure.

@ArtificialPB you can read from the cache manually in v6.

**Comment by ArtificialPB** [comment]
I support the request @Logicail made about being able to load custom definitions. 

@Logicail I thought that security manager blocks it.

**Comment by Timer** [comment]
Ask for things individually and they'll be added (issue for each cache field). Closing this because of its ambiguity.

**Comment by ArtificialPB** [comment]
Will we still be able to use our own cache readers in v7 or will the security manager block it? @Timer

**Comment by Timer** [comment]
We're going to probably end up removing the security manager and auditing scripts server side. So...
